### ISSUE TITLE
Cant start servers.

### ISSUE THREAD

**Issue by raventh1984** [Eastrall/Hellion#58]
Hi,
Well after i redit my hard drive cause of an crash. I no longer can start the servers.
Cloned the repositary again.
Did all the steps.

Launched restore.bat
Error that comes up

Error: ./../Src/Hellion.Core/project.json 
the rest is the same error.
So it cant find project.json

I alreayd searched the entire repository however its not there.
So i thought well maybe i need to re-build it again using vs2017.
Still no project files.

am i missing somewhat?

**Comment by Eastrall** [comment]
Hi, thanks for pointing this out. Indeed, that a problem of the `restore.bat` script.

Since, we've migrated to Visual Studio 2017, all `project.json` doens't exists anymore. Microsoft choose to abandon this type of file format and now they introduced again the `.csproj`.

I'll do a quick fix for the `restore.bat`.

**Comment by Eastrall** [comment]
Should be fixed with this commit : https://github.com/Eastrall/Hellion/commit/313c5c74f9ee87e6be44d0bbbd064023a5d22f2a

Let me know if you still have any problems.

**Comment by raventh1984** [comment]
Hi already tried that.

Error that comes out

Error: Invalid input './../src/Hellion.Core/Hellion.Core.csproj' The file type was not recognized.
Also for the other ones.

**Comment by raventh1984** [comment]
Solved by using the latest version of .net core sdk https://www.microsoft.com/net/download/core
